# -*- coding: utf-8 -*-
"""task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LaMb1kV_uH_xd7Y77ngd9DcTxkwcqT5X
"""

import requests
import matplotlib.pyplot as plt
from datetime import datetime

API_KEY = 'your_api_key'  # Replace with your OpenWeatherMap API key
CITY = 'London'
URL = f'http://api.openweathermap.org/data/2.5/forecast?q={CITY}&cnt=7&units=metric&appid={API_KEY}'

# Send GET request to the API
response = requests.get(URL)

# Check if the request was successful
if response.status_code == 200:
    data = response.json()

    dates = []
    temperatures = []

    for item in data['list']:
        # Convert timestamp to a readable date
        date = datetime.utcfromtimestamp(item['dt']).strftime('%Y-%m-%d')
        temperature = item['main']['temp']

        dates.append(date)
        temperatures.append(temperature)

    plt.figure(figsize=(10, 6))
    plt.plot(dates, temperatures, marker='o', color='b', linestyle='-', label='Temperature (°C)')

    plt.title(f'Temperature Trends for {CITY} (Next 7 Days)', fontsize=14)
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Temperature (°C)', fontsize=12)
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    plt.legend()

    # Show the plot
    plt.show()

else:
    print(f"Error fetching data from API. Status code: {response.status_code}")